apiVersion: app/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
    labels:
      app: nginx
    spec:
      nodeSelector:
      cloud.google.com/gke-nodepool: aplication-pool
    containers:
    - name: nginx
      image: nginx:1.14.2
      ports:
      - containerPort: 80
      resources:
        requests:
        cpu: "100m"
        limits:
        cpu: "200m"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 25




